x-timezone-env-var: &timezone-env-var TZ=Etc/UTC

x-common-logging: &common-logging
  logging:
    driver: 'json-file'
    options:
      max-size: 10m
      max-file: '3'

x-common-config: &common-config
  profiles:
    - prod
  environment:
    - *timezone-env-var
  restart: unless-stopped
  <<: *common-logging

services:
  pangolin:
    image: fosrl/pangolin:1.5.0
    hostname: pangolin
    <<: [*common-config]
    networks:
      - bridge_net_1
    environment:
      - USERS_SERVERADMIN_EMAIL=${USERS_SERVERADMIN_EMAIL}
      - USERS_SERVERADMIN_PASSWORD=${USERS_SERVERADMIN_PASSWORD}
    volumes:
      - ./config/pangolin:/app/config
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/api/v1/']
      interval: '3s'
      timeout: '3s'
      retries: 15
  gerbil:
    image: fosrl/gerbil:1.0.0
    hostname: gerbil
    <<: [*common-config]
    depends_on:
      pangolin:
        condition: service_healthy
    networks:
      - bridge_net_1
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - ./config/pangolin:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 80:80
      - 443:443
      - 8080:8080
  traefik:
    image: traefik:v3.4.0
    <<: [*common-config]
    network_mode: service:gerbil
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/config.yml
    volumes:
      - ./config/traefik:/etc/traefik:ro
      - ./config/traefik/letsencrypt:/letsencrypt

networks:
  bridge_net_1:
    driver: bridge
    attachable: true
