version: "3.8"

x-common-user-config: &common-config
  user: 1000:1000
  networks:
    - bridge_net_1
  restart: unless-stopped

x-timezone-env-var: &timezone-env-var TZ=Etc/UTC

x-common-media-volume: &common-media-volume /media/mediaserver:/media

x-common-download-volume: &common-download-volume /media/mediaserver/MediaShare/Downloads:/downloads

x-common-logging: &common-logging
  logging:
    driver: "json-file"
    options:
      max-size: 10m
      max-file: "3"

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    <<: *common-logging
    user: 1000:1000
    command: tunnel --no-autoupdate run
    environment:
      - *timezone-env-var
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    volumes:
      - ./config/cloudflared:/etc/cloudflared
    networks:
      - bridge_net_1
    restart: unless-stopped
  # duplicati:
  #   image: lscr.io/linuxserver/duplicati:latest
  #   <<: *common-logging
  #   hostname: duplicati
  #   user: 1000:1000
  #   environment:
  #     - *timezone-env-var
  #     - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_ENC_KEY}
  #   volumes:
  #     # - ./config:/source
  #     - ./compose.yml:/source/docker-compose.yml
  #     - ./config/duplicati/config:/config
  #     - ./config/duplicati/restore:/restore
  #   networks:
  #     - bridge_net_1
  #   ports:
  #     - 7001:8200
  #   restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    <<: *common-logging
    hostname: transmission
    user: 1000:1000
    environment:
      - *timezone-env-var
      # - TRANSMISSION_WEB_HOME= #optional
      - USER=mediaserver
      - PASS=pass@123
      # - WHITELIST= #optional
      # - PEERPORT= #optional
      # - HOST_WHITELIST= #optional
    volumes:
      - ./config/transmission:/config
      - *common-download-volume
    networks:
      - bridge_net_1
    ports:
      - 7002:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    <<: *common-logging
    hostname: nzbget
    user: 1000:1000
    environment:
      - *timezone-env-var
      - NZBGET_USER=mediaserver
      - NZBGET_PASS=pass@123
    volumes:
      - ./config/nzbget:/config
      - *common-download-volume
    networks:
      - bridge_net_1
    ports:
      - 7003:6789
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    <<: *common-logging
    hostname: qbittorrent
    user: 1000:1000
    environment:
      - *timezone-env-var
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - *common-download-volume
    networks:
      - bridge_net_1
    ports:
      - 7004:8080
      - 6881:6881/tcp
      - 6881:6881/udp
    restart: unless-stopped
  postgres:
    image: postgres:15
    <<: *common-logging
    hostname: postgres
    environment:
      PGUSER: mealie
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: pass@123
    volumes:
      - ./config/mealie/pgdata:/var/lib/postgresql/data
    networks:
      - bridge_net_1
    ports:
      - 7005:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.8.0
    <<: *common-logging
    hostname: mealie
    user: 1000:1000
    environment:
      - *timezone-env-var
      - ALLOW_SIGNUP=false
      - BASE_URL=https://mealie.yourdomain.com
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=pass@123
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    volumes:
      - ./config/mealie/appdata:/app/data/
    networks:
      - bridge_net_1
    ports:
      - 7101:9000
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1000M
    depends_on:
      - postgres
  # jellyfin:
  #   image: jellyfin/jellyfin
  #   <<: *common-logging
  #   hostname: jellyfin
  #   user: 1000:1000
  #   environment:
  #     - *timezone-env-var
  #     - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
  #     - JELLYFIN_CONFIG_DIR=/etc/jellyfin
  #     - JELLYFIN_DATA_DIR=/var/lib/jellyfin
  #     - JELLYFIN_LOG_DIR=/var/log/jellyfin
  #   volumes:
  #     - ./config/jellyfin/etc:/etc/jellyfin
  #     - ./config/jellyfin/var-cache:/var/cache/jellyfin
  #     - ./config/jellyfin/var-lib:/var/lib/jellyfin
  #     - ./config/jellyfin/var-log:/var/log/jellyfin
  #     - ./config/jellyfin/timezone:/etc/timezone
  #   group_add:
  #     - "109"
  #   network_mode: "host"
  #   ports:
  #     - 8000:8096
  #   devices:
  #     - /dev/dri/renderD128:/dev/dri/renderD128
  #   restart: unless-stopped
  prowlarr:
    image: linuxserver/prowlarr:latest
    <<: *common-logging
    hostname: prowlarr
    user: 1000:1000
    environment:
      - *timezone-env-var
    volumes:
      - ./config/prowlarr:/config
    networks:
      - bridge_net_1
    ports:
      - 8002:9696
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    <<: *common-logging
    hostname: radarr
    user: 1000:1000
    environment:
      - *timezone-env-var
    volumes:
      - ./config/radarr:/config
      - *common-download-volume
      - *common-media-volume
    networks:
      - bridge_net_1
    ports:
      - 8101:7878
    restart: unless-stopped
    depends_on:
      # - jellyfin
      - transmission
      - prowlarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    <<: *common-logging
    hostname: sonarr
    user: 1000:1000
    environment:
      - *timezone-env-var
    volumes:
      - ./config/sonarr:/config
      - *common-download-volume
      - *common-media-volume
    networks:
      - bridge_net_1
    ports:
      - 8102:8989
    restart: unless-stopped
    depends_on:
      # - jellyfin
      - transmission
      - prowlarr
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    <<: *common-logging
    hostname: lidarr
    user: 1000:1000
    environment:
      - *timezone-env-var
    volumes:
      - ./config/lidarr:/config
      - *common-download-volume
      - *common-media-volume
    networks:
      - bridge_net_1
    ports:
      - 8103:8686
    restart: unless-stopped
    depends_on:
      # - jellyfin
      - transmission
      - prowlarr
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    <<: *common-logging
    hostname: readarr
    user: 1000:1000
    environment:
      - *timezone-env-var
    volumes:
      - ./config/readarr:/config
      - *common-download-volume
      - *common-media-volume
    networks:
      - bridge_net_1
    ports:
      - 8104:8787
    restart: unless-stopped
    depends_on:
      # - jellyfin
      - transmission
      - prowlarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    <<: *common-logging
    hostname: bazarr
    user: 1000:1000
    environment:
      - *timezone-env-var
    volumes:
      - ./config/bazarr:/config
      - *common-download-volume
      - *common-media-volume
    networks:
      - bridge_net_1
    ports:
      - 8201:6767
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    <<: *common-logging
    hostname: jellyseerr
    user: 1000:1000
    environment:
      - *timezone-env-var
    volumes:
      - ./config/jellyseerr:/app/config
    networks:
      - bridge_net_1
    ports:
      - 8202:5055
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
  # lunasea:
  #   image: ghcr.io/jagandeepbrar/lunasea:stable
  #   <<: *common-logging
  #   hostname: lunasea
  #   user: 1000:1000
  #   environment:
  #     - *timezone-env-var
  #   volumes:
  #     - ./config/lunasea:/config
  #   networks:
  #     - bridge_net_1
  #   ports:
  #     - 8203:80
  #   restart: unless-stopped
  #   depends_on:
  #     - radarr
  #     - sonarr
  #     - lidarr
  #     - readarr
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    <<: *common-logging
    hostname: homarr
    environment:
      - SECRET_ENCRYPTION_KEY=${HOMARR_ENC_KEY}
    volumes:
      - ./custom_entrypoint.sh/:/data/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/homarr/appdata:/appdata
    networks:
      - bridge_net_1
    ports:
      - "8080:7575"
    # entrypoint: source /data/custom_entrypoint.sh
    restart: unless-stopped

networks:
  bridge_net_1:
    driver: bridge
    attachable: true
