version: "3.8"

x-timezone-env-var: &timezone-env-var TZ=Etc/UTC

x-common-media-volume: &common-media-volume /media/mediaserver:/media

x-common-download-volume: &common-download-volume /media/mediaserver/MediaShare/Downloads:/downloads

x-common-logging: &common-logging
  logging:
    driver: "json-file"
    options:
      max-size: 10m
      max-file: "3"

x-common-config: &common-config
  networks:
    - bridge_net_1
  # user: 1000:1000
  profiles:
    - prod
  restart: unless-stopped
  <<: *common-logging

x-common-network: &common-network
  networks:
    - bridge_net_1

services:
  # duplicati:
  #   image: lscr.io/linuxserver/duplicati:latest
  #   hostname: duplicati
  #   <<: *common-config
  #   user: 1000:1000
  #   environment:
  #     - *timezone-env-var
  #     - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_ENC_KEY}
  #   volumes:
  #     # - ./config:/source
  #     - ./compose.yml:/source/docker-compose.yml
  #     - ./config/duplicati/config:/config
  #     - ./config/duplicati/restore:/restore
  #   networks:
  #     - bridge_net_1
  #   ports:
  #     - 7001:8200
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    hostname: transmission
    <<: *common-config
    user: 1000:1000
    environment:
      - *timezone-env-var
      # - TRANSMISSION_WEB_HOME= #optional
      - USER=mediaserver
      - PASS=pass@123
      # - WHITELIST= #optional
      # - PEERPORT= #optional
      # - HOST_WHITELIST= #optional
    volumes:
      - ./config/transmission:/config
      - *common-download-volume
    networks:
      - bridge_net_1
    ports:
      - 7002:9091
      - 51413:51413
      - 51413:51413/udp
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    hostname: nzbget
    <<: *common-config
    user: 1000:1000
    environment:
      - *timezone-env-var
      - NZBGET_USER=mediaserver
      - NZBGET_PASS=pass@123
    volumes:
      - ./config/nzbget:/config
      - *common-download-volume
    networks:
      - bridge_net_1
    ports:
      - 7003:6789
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    hostname: qbittorrent
    <<: *common-config
    user: 1000:1000
    environment:
      - *timezone-env-var
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - *common-download-volume
    networks:
      - bridge_net_1
    ports:
      - 7004:8080
      - 6881:6881/tcp
      - 6881:6881/udp
  postgres:
    image: postgres:15
    hostname: postgres
    <<: *common-config
    environment:
      PGUSER: mealie
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: pass@123
    volumes:
      - ./config/mealie/pgdata:/var/lib/postgresql/data
    networks:
      - bridge_net_1
    ports:
      - 7005:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.8.0
    hostname: mealie
    <<: *common-config
    user: 1000:1000
    environment:
      - *timezone-env-var
      - ALLOW_SIGNUP=false
      - BASE_URL=https://mealie.yourdomain.com
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=pass@123
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    volumes:
      - ./config/mealie/appdata:/app/data/
    networks:
      - bridge_net_1
    ports:
      - 7101:9000
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1000M
    depends_on:
      - postgres
  # jellyfin:
  #   image: jellyfin/jellyfin
  #   <<: *common-logging
  #   hostname: jellyfin
  #   user: 1000:1000
  #   environment:
  #     - *timezone-env-var
  #     - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
  #     - JELLYFIN_CONFIG_DIR=/etc/jellyfin
  #     - JELLYFIN_DATA_DIR=/var/lib/jellyfin
  #     - JELLYFIN_LOG_DIR=/var/log/jellyfin
  #   volumes:
  #     - ./config/jellyfin/etc:/etc/jellyfin
  #     - ./config/jellyfin/var-cache:/var/cache/jellyfin
  #     - ./config/jellyfin/var-lib:/var/lib/jellyfin
  #     - ./config/jellyfin/var-log:/var/log/jellyfin
  #     - ./config/jellyfin/timezone:/etc/timezone
  #   group_add:
  #     - "109"
  #   network_mode: "host"
  #   ports:
  #     - 8000:8096
  #   devices:
  #     - /dev/dri/renderD128:/dev/dri/renderD128
  prowlarr:
    image: linuxserver/prowlarr:latest
    hostname: prowlarr
    <<: *common-config
    user: 1000:1000
    environment:
      - *timezone-env-var
    volumes:
      - ./config/prowlarr:/config
    networks:
      - bridge_net_1
    ports:
      - 8002:9696
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    hostname: radarr
    <<: *common-config
    user: 1000:1000
    environment:
      - *timezone-env-var
    volumes:
      - ./config/radarr:/config
      - *common-download-volume
      - *common-media-volume
    networks:
      - bridge_net_1
    ports:
      - 8101:7878
    depends_on:
      # - jellyfin
      - transmission
      - prowlarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    hostname: sonarr
    <<: *common-config
    user: 1000:1000
    environment:
      - *timezone-env-var
    volumes:
      - ./config/sonarr:/config
      - *common-download-volume
      - *common-media-volume
    networks:
      - bridge_net_1
    ports:
      - 8102:8989
    depends_on:
      # - jellyfin
      - transmission
      - prowlarr
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    hostname: lidarr
    <<: *common-config
    user: 1000:1000
    environment:
      - *timezone-env-var
    volumes:
      - ./config/lidarr:/config
      - *common-download-volume
      - *common-media-volume
    networks:
      - bridge_net_1
    ports:
      - 8103:8686
    depends_on:
      # - jellyfin
      - transmission
      - prowlarr
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    hostname: readarr
    <<: *common-config
    user: 1000:1000
    environment:
      - *timezone-env-var
    volumes:
      - ./config/readarr:/config
      - *common-download-volume
      - *common-media-volume
    networks:
      - bridge_net_1
    ports:
      - 8104:8787
    depends_on:
      # - jellyfin
      - transmission
      - prowlarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    hostname: bazarr
    <<: *common-config
    user: 1000:1000
    environment:
      - *timezone-env-var
    volumes:
      - ./config/bazarr:/config
      - *common-download-volume
      - *common-media-volume
    networks:
      - bridge_net_1
    ports:
      - 8201:6767
    depends_on:
      - radarr
      - sonarr
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    hostname: jellyseerr
    <<: *common-config
    user: 1000:1000
    environment:
      - *timezone-env-var
    volumes:
      - ./config/jellyseerr:/app/config
    networks:
      - bridge_net_1
    ports:
      - 8202:5055
    depends_on:
      - radarr
      - sonarr
  # lunasea:
  #   image: ghcr.io/jagandeepbrar/lunasea:stable
  #   hostname: lunasea
  #   <<: *common-config
  #   user: 1000:1000
  #   environment:
  #     - *timezone-env-var
  #   volumes:
  #     - ./config/lunasea:/config
  #   networks:
  #     - bridge_net_1
  #   ports:
  #     - 8203:80
  #   depends_on:
  #     - radarr
  #     - sonarr
  #     - lidarr
  #     - readarr
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    hostname: homarr
    <<: *common-config
    environment:
      - SECRET_ENCRYPTION_KEY=${HOMARR_ENC_KEY}
    volumes:
      - ./custom_entrypoint.sh/:/data/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/homarr/appdata:/appdata
    networks:
      - bridge_net_1
    ports:
      - "8080:7575"
  # the-market-diary:
  #   image: ghcr.io/jitendrasachwani/jitendrasachwani/the-market-diary:latest
  #   hostname: the-market-diary
  #   <<: *common-config
  #   user: 1000:1000
  #   environment:
  #     - DOCKER_REGISTRY_USERNAME=${DOCKER_REGISTRY_USERNAME}
  #     - DOCKER_REGISTRY_PASSWORD=${DOCKER_REGISTRY_PASSWORD}
  #     - *timezone-env-var
  #     - NODE_ENV=production
  #   volumes:
  #     - ../the-market-diary/public/videos:/app/public/videos
  #     - ../the-market-diary/out/bundle:/app/out/bundle
  #   networks:
  #     - bridge_net_1
  #   ports:
  #     - "3000:3000"
  #     - "3001:3001"

  # ALWAYS KEEP THIS AS THE LAST SERVICE IN THE FILE AND ADD ALL DEPENDENCIES IN THE DEPENDS_ON SECTION
  newt:
    image: fosrl/newt:latest
    hostname: newt
    <<: *common-config
    profiles:
      - dev
    environment:
      - PANGOLIN_ENDPOINT=${NEWT_ENDPOINT}
      - NEWT_ID=${NEWT_ID}
      - NEWT_SECRET=${NEWT_SECRET}
      - LOG_LEVEL=DEBUG
    # TODO: Test all one by one and uncomment
    # depends_on:
    #   - homarr
    #   - radarr
    #   - sonarr
    #   - lidarr
    #   - readarr
    #   - bazarr
    #   - jellyseerr
    #   - jellyfin
    #   - prowlarr
    #   - transmission
    #   - nzbget
    #   - qbittorrent
    #   - mealie
    #   - duplicati
    #   - postgres
    #   - the-market-diary
    #   - lunasea
  # DO NOT ADD ANY SERVICES BELOW THE NEWT SERVICE, ADD THEM ABOVE THIS SERVICE IF NEEDED

networks:
  bridge_net_1:
    driver: bridge
    attachable: true
